### ISSUE TITLE
Make antialiasing work

### ISSUE THREAD

**Issue by buddebej** [buddebej/elasticterrain#24]

**Comment by berniejenny** [comment]
Many browsers do not currently support anti-aliasing. Probably there is nothing that one can do about this.

**Comment by buddebej** [comment]
http://codeflow.org/entries/2013/feb/22/how-to-write-portable-webgl/#antialiasing

How to deal with no antialiasing?
Aparts from simply ignoring the problem and accepting the degraded quality, there are ways to supply your own antialiasing.

You can implement super sample antialias (SSAA) by either rendering your scene at twice or four times the size and then downscale, or by rendering the scene 4 or 16 times with small offsets applied to the device normal coordinate.

You can implement morphological antialiasing
An edge detection (such as sobel or laplace) can be used on the depth and/or normals to compute weights for a gaussian blur.

Any of the above methods may be accelerated by multi-frame accumulation and temporal reprojection.

There are many more subtle ways to achieve antialiasing, those are just the most obvious.
