### ISSUE TITLE
Unsatisfied dependency

### ISSUE THREAD

**Issue by salmanb1** [buddebej/elasticterrain#30]
I ran 'make install' and 'make serve' commands on a Linux machine.
When running this project locally, I tried accessing the elasticterrain.html file. The following error showed up in the command prompt:
**Unsatisfied dependency "ol.renderer.webgl.tiledemlayer.shader" in script: ........./elasticterrain-master/ol3/src/ol/renderer/webgl/webgltiledemlayerrenderer.js**

Do you have any idea how to solve this error? Should I run this project in a different OS?

**Comment by buddebej** [comment]
Hi salmanb1,

Thank you very much for your interest in our project and your error
report. You should try to run "make build" or "make shaders" before
running make serve.

Take a look at the makefile if you are interested in how this routines
work:

https://github.com/buddebej/elasticterrain/blob/master/ol3/Makefile

Best regards,

Jonas
